elasticsearch:
  image: "elasticsearch:latest"
  container_name: elasticsearch
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  restart: always
  volumes:
    - .:/elasticsearch/data
kibana:
  image: "kibana:latest"
  container_name: kibana
  ports:
    - "5601:5601"
  restart: always
  volumes:
    - .:/kibana/data
  links:
    - elasticsearch
